name: Gestao de vagas application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - run: mvn clean install
    - name: login docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: build docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gestao-vagas:latest .

    - name: push docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/gestao-vagas:latest
