name: Gestao de Vagas Application


on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                 distribution: temurin
                 java-version: 21
            - name: Build project
              run: mvn clean install
            - name: Login docker
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_USERNAME}}/gestao_vagas .
            - name: Publish image
              run: docker push ${{secrets.DOCKER_USERNAME}}/gestao_vagas
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Remove container
              run: docker rm -f gestao-vagas || true
            
            - name: Run docker container gestao-vagas
              run: |
                docker run -d -p 8080:8080 \
                  -e DATABASE_URL="${secrets.DATABASE_URL}" \
                  -e DATABASE_USERNAME="${secrets.DATABASE_USERNAME}" \
                  -e DATABASE_PASSWORD="${secrets.DATABASE_PASSWORD}" \
                  -e SPRING_DATASOURCE_SSL_MODE="require" \
                  --name gestao-vagas \
                  ${{secrets.DOCKER_USERNAME}}/gestao_vagas
                
                # Wait for container to start and show logs
                sleep 10
                docker logs gestao-vagas
              
    